- name: Chrome ve Driver Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Kütüphaneleri Kur
        run: |
          pip install selenium webdriver-manager requests
      - name: Botu Çalıştır
        run: python bot.py
